AY1920S1-CS2113T-W17-3/main

src/main/java/duke/command/DeleteCommand.java, src/main/java/duke/command/DoneCommand.java, src/main/java/duke/parse/Parser.java, src/main/java/duke/task/Deadline.java, src/main/java/duke/task/Event.java, src/test/java/duke/storage/StorageTest.java, src/test/java/duke/task/TaskListTest.java, src/test/java/duke/task/TaskTest.java
There were a couple of typos that were detected and have been fixed
Resolves: #3
=> Fix error messages for wrong inputs

config/checkstyle/checkstyle.xml
Checkstyle has been implemented, current code quality is checkstyle passable.
Check using: gradlew CheckstyleMain
=> [CS2113T-W17-3]-shamussy-A-CheckStyle

.travis.yml, src/test/java/duke/MainTest.java
Implement travis ci to facilitate CI in the long run.
=> [CS2113T-W17-3]-shamussy-A-Travis

src/main/java/duke/command/ReminderCommand.java, src/main/java/duke/parse/Parser.java, src/main/java/duke/task/Deadline.java, src/main/java/duke/task/Event.java, src/main/java/duke/task/Task.java, src/main/java/duke/task/TaskList.java, src/test/java/duke/MainTest.java, src/test/java/duke/command/ReminderCommandTest.java
This commit contains the reminder function created in
ReminderCommand.java file.
=> [CS2113T-W17-3]-mong-nus-B-Reminders

src/main/java/duke/command/ViewCommand.java, src/main/java/duke/parse/Parser.java, src/main/java/duke/task/Deadline.java, src/main/java/duke/task/Event.java, src/main/java/duke/task/Task.java, src/main/java/duke/task/TaskList.java, src/test/java/duke/MainTest.java, src/test/java/duke/command/ViewCommandTest.java
=> [CS2113T-W17-3]-valerietyj-B-ViewSchedules

docs/AboutUs.adoc, src/main/java/owlmoney/Main.java, src/main/java/owlmoney/logic/command/exception/commandException.java, src/main/java/owlmoney/logic/parser/ParseCommand.java, src/main/java/owlmoney/logic/parser/ParseRawData.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/Parser.java, src/main/java/owlmoney/logic/parser/exception/ParserException.java, src/main/java/owlmoney/ui/Ui.java
This commit is ready for further development with regards to parsing raw
data
=> Update initial phase for OwlMoney baseline with basic parsing

src/main/java/owlmoney/logic/parser/ParseCommand.java, src/main/java/owlmoney/logic/parser/ParseRawData.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/saving/ParseAddSaving.java, src/main/java/owlmoney/logic/parser/saving/ParseEditSaving.java, src/main/java/owlmoney/logic/parser/saving/ParseSaving.java
Here is the code for Parser implementation.
=> Implement ParseRawData and ParseSaving

src/main/java/owlmoney/Main.java, src/main/java/owlmoney/logic/command/bank/AddSavingsCommand.java, src/main/java/owlmoney/logic/command/bank/DeleteSavingsCommand.java, src/main/java/owlmoney/logic/parser/ParseCommand.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/Parser.java, src/main/java/owlmoney/logic/parser/saving/ParseAddSaving.java, src/main/java/owlmoney/logic/parser/saving/ParseDeleteSaving.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/profile/Profile.java, src/main/java/owlmoney/ui/Ui.java
This commit contains the function of creating a profile, adding and deleting of the savings account
=> Implemented adding and deleting of savings

src/main/java/owlmoney/logic/command/expenditure/AddExpenditureCommand.java, src/main/java/owlmoney/logic/parser/ParseCommand.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/expenditure/ParseAddExpenditure.java, src/main/java/owlmoney/logic/parser/expenditure/ParseExpenditure.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/expenditure/Expenditure.java, src/main/java/owlmoney/model/expenditure/ExpenditureList.java, src/main/java/owlmoney/model/profile/Profile.java
This commit contain the function to add expenditure to saving accounts.
=> Implement Add function for Expenditure to Saving Account

docs/DeveloperGuide.adoc, docs/UserGuide.adoc
Resolves #62 
UML Diagrams not required for v1.1 yet. Will proceed to do it for 1.2 onwards.
Major UG Updates that includes command syntaxes
special thanks to @valerietyj  and @mong-nus  for brainstorming the commands and syntaxes as well.
=> Morphbaseline

src/main/java/owlmoney/Main.java, src/main/java/owlmoney/logic/command/OwlMoneyCommand.java, src/main/java/owlmoney/logic/command/PlaceHolderEmptyCommand.java, src/main/java/owlmoney/logic/command/bank/AddSavingsCommand.java, src/main/java/owlmoney/logic/command/bank/DeleteSavingsCommand.java, src/main/java/owlmoney/logic/command/bank/ListSavingsCommand.java, src/main/java/owlmoney/logic/command/expenditure/AddExpenditureCommand.java, src/main/java/owlmoney/logic/command/expenditure/DeleteExpenditureCommand.java, src/main/java/owlmoney/logic/command/expenditure/ListExpenditureCommand.java, src/main/java/owlmoney/logic/parser/ParseCommand.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/Parser.java, src/main/java/owlmoney/logic/parser/expenditure/ParseAddExpenditure.java, src/main/java/owlmoney/logic/parser/expenditure/ParseDeleteExpenditure.java, src/main/java/owlmoney/logic/parser/expenditure/ParseExpenditure.java, src/main/java/owlmoney/logic/parser/expenditure/ParseListExpenditure.java, src/main/java/owlmoney/logic/parser/saving/ParseAddSaving.java, src/main/java/owlmoney/logic/parser/saving/ParseDeleteSaving.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/expenditure/Expenditure.java, src/main/java/owlmoney/model/expenditure/ExpenditureList.java, src/main/java/owlmoney/model/profile/Profile.java
This commit contains the code for deleting expenditure and listing savings and expenditure.
=> Implement delete expenditure and list savings and expenditure

build.gradle, src/main/java/owlmoney/logic/regex/Regex.java, src/main/java/owlmoney/logic/regex/RegexUtil.java
This PR should contain basic regex for many of the parsing required.
Yet to add dates yet.
=> Add basic regex check for base features

src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/transaction/Transaction.java, src/main/java/owlmoney/model/transaction/TransactionList.java
This PR checks if bank name is unique before adding into the list. Also prints '$' for money
Resolves #24 , Resolves #26 , Resolves #27 , Resolves #28
=> Fixed uniqueness of bank name

src/main/java/owlmoney/logic/command/card/EditCardCommand.java, src/main/java/owlmoney/logic/parser/card/ParseEditCard.java, src/main/java/owlmoney/model/card/Card.java, src/main/java/owlmoney/model/card/CardList.java, src/main/java/owlmoney/model/profile/Profile.java, src/main/java/owlmoney/model/transaction/TransactionList.java
This implementation documents the javadoc and also correct some of the error message to be thrown for the card features.
=> Documents the JavaDoc and Correct Error Message for Card Features

src/main/java/owlmoney/logic/command/bank/AddInvestmentCommand.java, src/main/java/owlmoney/logic/command/bank/AddSavingsCommand.java, src/main/java/owlmoney/logic/command/bank/DeleteInvestmentCommand.java, src/main/java/owlmoney/logic/command/bank/DeleteSavingsCommand.java, src/main/java/owlmoney/logic/command/bank/EditInvestmentCommand.java, src/main/java/owlmoney/logic/command/bank/EditSavingsCommand.java, src/main/java/owlmoney/logic/command/bank/ListInvestmentCommand.java, src/main/java/owlmoney/logic/command/bank/ListSavingsCommand.java, src/main/java/owlmoney/logic/command/card/AddCardCommand.java, src/main/java/owlmoney/logic/command/card/DeleteCardCommand.java, src/main/java/owlmoney/logic/command/card/EditCardCommand.java, src/main/java/owlmoney/logic/command/card/ListCardCommand.java, src/main/java/owlmoney/logic/command/transaction/AddDepositCommand.java, src/main/java/owlmoney/logic/command/transaction/AddExpenditureCommand.java, src/main/java/owlmoney/logic/command/transaction/DeleteDepositCommand.java, src/main/java/owlmoney/logic/command/transaction/DeleteExpenditureCommand.java, src/main/java/owlmoney/logic/command/transaction/EditDepositCommand.java, src/main/java/owlmoney/logic/command/transaction/EditExpenditureCommand.java, src/main/java/owlmoney/logic/command/transaction/ListDepositCommand.java, src/main/java/owlmoney/logic/command/transaction/ListExpenditureCommand.java, src/main/java/owlmoney/model/card/CardList.java, src/main/java/owlmoney/model/profile/Profile.java
This commit implements a new function to check whether the name of a new card to be added already exist. If exist, it will throw an error as only unique card name is allowed. 
There are also missing javadoc in bank, transaction and card package under logic. This commit also add in the missing javadoc for everyone. 
Collaborated with @TerenceTanWT
=> Implemented Check Duplicate Card Name and Add missing Javadoc

src/main/java/owlmoney/model/card/CardList.java
This commit contains the function to check for duplicate credit card name when editing cards details.
=> Implement function to check for duplicate name in edit credit card

docs/DeveloperGuide.adoc, docs/UserGuide.adoc
New command syntax, organisation of commands and parameters for each category has been added.
=> Update user guide and developer guide with new command syntax

src/main/java/owlmoney/model/card/Card.java, src/main/java/owlmoney/model/card/CardList.java, src/main/java/owlmoney/model/transaction/Transaction.java, src/main/java/owlmoney/model/transaction/TransactionList.java
Resolves #104
Previous implementation of credit card limit was only temporary. Re-implemented credit card limit checking based on monthly card expenditures. Collaborated with @mong-nus.
=> Fixed credit card limit not based on monthly card expenditures.

src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/bond/ParseBond.java, src/main/java/owlmoney/logic/parser/card/ParseCard.java, src/main/java/owlmoney/logic/parser/goals/ParseGoals.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/goals/Goals.java, src/main/java/owlmoney/model/goals/GoalsList.java
=> fix minor bug and javadocs

src/main/java/owlmoney/model/bank/Investment.java, src/main/java/owlmoney/model/bond/Bond.java, src/main/java/owlmoney/model/bond/BondList.java, src/main/java/owlmoney/model/profile/Profile.java, src/test/java/owlmoney/model/bank/InvestmentTest.java, src/test/java/owlmoney/model/bond/BondListStub.java, src/test/java/owlmoney/model/bond/BondListTest.java, src/test/java/owlmoney/model/bond/BondStub.java, src/test/java/owlmoney/model/bond/BondTest.java
=> Add functionality for bond interest

src/main/java/owlmoney/logic/command/find/FindTransactionCommand.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/profile/Profile.java
The group has decided to implement listing and finding of transaction for investment object. This pull request is to amend the code and allows the find feature to work on investment object as well.
=> Make amendment to allow finding of transaction

src/main/java/owlmoney/Main.java, src/main/java/owlmoney/MainException.java, src/main/java/owlmoney/logic/command/Command.java, src/main/java/owlmoney/logic/command/goals/AddGoalsCommand.java, src/main/java/owlmoney/logic/command/goals/DeleteGoalsCommand.java, src/main/java/owlmoney/logic/command/goals/EditGoalsCommand.java, src/main/java/owlmoney/logic/command/profile/EditProfileCommand.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/bond/ParseBond.java, src/main/java/owlmoney/logic/parser/card/ParseCard.java, src/main/java/owlmoney/logic/parser/find/ParseFind.java, src/main/java/owlmoney/logic/parser/goals/ParseGoals.java, src/main/java/owlmoney/logic/parser/investment/ParseInvestment.java, src/main/java/owlmoney/logic/parser/profile/ParseEditProfile.java, src/main/java/owlmoney/logic/parser/saving/ParseSaving.java, src/main/java/owlmoney/logic/parser/transaction/deposit/ParseDeposit.java, src/main/java/owlmoney/logic/parser/transaction/expenditure/ParseExpenditure.java, src/main/java/owlmoney/logic/parser/transfer/ParseTransfer.java, src/main/java/owlmoney/model/goals/Goals.java, src/main/java/owlmoney/model/profile/Profile.java, src/main/java/owlmoney/model/profile/exception/ProfileException.java, src/test/java/owlmoney/model/goals/GoalsTest.java
=> Implement edit profile name and fix bugs for profile.

build.gradle, src/main/java/owlmoney/Main.java, src/main/java/owlmoney/logic/command/profile/EditProfileCommand.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Investment.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/bond/BondList.java, src/main/java/owlmoney/model/card/CardList.java, src/main/java/owlmoney/model/goals/GoalsList.java, src/main/java/owlmoney/model/profile/Profile.java, src/main/java/owlmoney/model/transaction/RecurringExpenditureList.java, src/main/java/owlmoney/model/transaction/Transaction.java, src/main/java/owlmoney/model/transaction/TransactionList.java, src/main/java/owlmoney/storage/Storage.java, src/test/java/owlmoney/model/bond/BondListStub.java
@BrianTKM Please help to test whether there are any bugs with regards to the storage features.
Currently the storage is implemented for savings and investment accounts as well as editing of profile name.
The nature of storage is that it inherently trusts what the user puts in the file (if he edits it), therefore, if malformed data is imported, the program might not perform well, other than that, please help to check if there are any issues when using normally.
If there are no other issues, I will need to work with @mong-nus  and @TerenceTanWT to save the cards as well as @valerietyj  to save bonds.
=> Persistent Storage for savings, investment, bonds, profile.

src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/card/CardList.java, src/test/java/owlmoney/model/card/CardTest.java, src/test/java/owlmoney/model/find/FindTest.java, src/test/java/owlmoney/model/transfer/TransferFundTest.java
This commit consist of the Junit Testing Code for Card, Find and Transfer Feature. Collaborated with @TerenceTanWT.
=> Implement Junit Testing for Card, Find and Transfer

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/goals/Goals.java, src/main/java/owlmoney/model/goals/GoalsList.java, src/main/java/owlmoney/model/profile/Profile.java
Remaining features that do not have persistent storage are cards.
=> Implement persistent storage for goals and transfer functions

src/test/java/owlmoney/model/bank/SavingTest.java
Hard coded date so that test will be consistent
=> fix failing JUnit

docs/UserGuide.adoc, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Investment.java, src/main/java/owlmoney/model/profile/Profile.java
=> Hotfix for bonds interest

src/main/java/owlmoney/model/card/Card.java, src/main/java/owlmoney/model/card/CardList.java, src/main/java/owlmoney/model/profile/Profile.java, src/test/java/owlmoney/model/card/CardExpenditureTest.java, src/test/java/owlmoney/model/card/CardTest.java
Implemented JUnit for Card.java to provide unit testing for functions related to card expenditures and card bills.
Also resolves #99 integer overflow bug for card list. Fixed integer overflow bug for card list by implementing a 10 card limit.
=> Implemented JUnit for Cards

docs/DeveloperGuide.adoc
Resolves #159 
Resolves #160 
Resolves #161 
This pull request resolve the above 3 issue in the developer guide.
=> Resolve developer guide issue for #159, #160, #161

docs/DeveloperGuide.adoc, src/test/java/owlmoney/model/bank/BankListTest.java
added back failing test cases due to failure to save on travis
=> added back test cases and corrected part of DG

src/main/java/owlmoney/logic/command/cardbill/AddCardBillCommand.java, src/main/java/owlmoney/model/card/Card.java, src/test/java/owlmoney/model/card/CardTest.java
Resolves #150
Resolves #154
Fixes bug #150 where credit card does not limit to 20% and credit card rebate was incorrectly calculated.
Fixes bug #154 so that when user list card expenditure, paid and unpaid expenditures are listed.
=> Fixes bug #150 and #154 related to card rebates and listing card expenditures

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/owlmoney/logic/command/find/FindRecurringExpenditureCommand.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/find/ParseFindRecurring.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/BankList.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/card/Card.java, src/main/java/owlmoney/model/profile/Profile.java, src/main/java/owlmoney/model/transaction/RecurringExpenditureList.java, src/main/java/owlmoney/model/transaction/TransactionList.java, src/test/java/owlmoney/model/bank/BankListTest.java, src/test/java/owlmoney/model/transaction/RecurringExpenditureListTest.java, src/test/java/owlmoney/model/transaction/TransactionListTest.java
Resolves #145 
Resolves #199 
This pull request consist of the implementation for finding recurring expenditure as well as paid expenditure in card. It also consist the Junit testing for find recurring expenditure. 
Find recurring expenditure documentation was also added to the UGDG.
=> Implement Find recurring expenditure and paid expenditure for card

docs/UserGuide.adoc, src/main/java/owlmoney/model/goals/Goals.java, src/main/java/owlmoney/model/goals/GoalsList.java
=> Allow user to untie savings account linked to goals

src/main/java/owlmoney/logic/command/cardbill/AddCardBillCommand.java, src/main/java/owlmoney/logic/command/help/HelpCommand.java, src/main/java/owlmoney/logic/parser/ParseCommand.java, src/main/java/owlmoney/logic/parser/Parser.java
Resolves #149 
Resolves #185 
Implemented help function /help to list all available commands.
=> Implemented Help Function

src/main/java/owlmoney/logic/command/cardbill/AddCardBillCommand.java, src/main/java/owlmoney/logic/command/cardbill/DeleteCardBillCommand.java, src/main/java/owlmoney/logic/parser/ParseRawData.java, src/main/java/owlmoney/logic/parser/ParseType.java, src/main/java/owlmoney/logic/parser/cardbill/ParseAddCardBill.java, src/main/java/owlmoney/logic/parser/cardbill/ParseCardBill.java, src/main/java/owlmoney/logic/parser/cardbill/ParseDeleteCardBill.java, src/main/java/owlmoney/model/bank/Bank.java, src/main/java/owlmoney/model/bank/Saving.java, src/main/java/owlmoney/model/card/Card.java, src/main/java/owlmoney/model/card/CardList.java, src/main/java/owlmoney/model/profile/Profile.java, src/test/java/owlmoney/model/card/CardTest.java
Implemented Logging for Cards and Storage.
Added JUnit for ParseRawData.
Renamed method isDeleteProfile in ParseType.java to checkDeleteProfile.
=> Implemented Logging for Cards and Storage, and added JUnit for ParseRawData

src/main/java/owlmoney/logic/regex/RegexUtil.java, src/main/java/owlmoney/model/profile/Profile.java
This commit fixes regex function to accept numbers such as 001
This commit fixes update message
=> Fix regex and update message

docs/UserGuide.adoc, src/main/java/owlmoney/logic/command/cardbill/AddCardBillCommand.java, src/main/java/owlmoney/logic/parser/cardbill/ParseCardBill.java, src/main/java/owlmoney/model/card/Card.java, src/main/java/owlmoney/model/profile/Profile.java
Fixed date parsing for card and cardbill where the program crashes when detected d/M/yyyy.
Edited printing and error messages to display MM/yyyy for card bill date instead of yyyy/MM.
=> Fixed various date parsing issues for card and cardbill

README.adoc, docs/DeveloperGuide.adoc, docs/team/shamussy.adoc, src/test/java/owlmoney/logic/parser/ParseCommandTest.java
=> Update DG, product website

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, docs/team/valerietyj.adoc, src/main/java/owlmoney/logic/regex/RegexUtil.java
Maintain consistency in size of sequence diagrams in DG, update format errors in UG and added missing javadocs in regex.
=> Minor edits to DG, UG and added missing Javadocs

docs/DeveloperGuide.adoc, docs/team/mong-nus.adoc, src/main/java/owlmoney/model/profile/Profile.java
The pull request amend the DG and my portfolio.
=> Update DG and PPP

docs/DeveloperGuide.adoc, src/main/java/owlmoney/logic/parser/transaction/expenditure/ParseExpenditure.java, src/main/java/owlmoney/logic/parser/transaction/expenditure/ParseRecurringExpenditure.java, src/main/java/owlmoney/model/bank/BankList.java
Fixed error message at ParseExpenditure and ParseRecurringExpenditure
=> Fix error message

docs/UserGuide.adoc, docs/team/terencetanwt.adoc
Fixed error in UG regrading delete cardbill syntax
=> Fixed error in UG regrading delete cardbill syntax

docs/DeveloperGuide.adoc
Edited manual testing cardbill date to 11/2019 instead of 10/2019.
=> Updated DG manual testing to update cardbill date
